### ISSUE TITLE
map different docker port then 80

### ISSUE THREAD

**Issue by bugs-404** [Activiti/activiti-cloud-examples#105]
First of all, if I follow the [developers guide](https://activiti.gitbook.io/activiti-7-developers-guide/getting-started/getting-started-activiti-cloud/getting-started-docker-compose), everything is fine.

 But if I make a few change of file **docker-compose.yml** at line 22~24 like this:
```
nginx:
...
  ports:
      - 8000:80
      - 8443:443
```
and save 
```
DOCKER_IP=192.168.1.114:8000
VERSION=7.1.0.M2
KEYCLOAK_REALM=activiti
KEYCLOAK_RESOURCE=activiti
```
as  **.env** .I got this error 

![image](https://user-images.githubusercontent.com/6689676/65006550-f0ebf380-d935-11e9-94c5-014be137f999.png)

Does this mean that we must map nginx container's  port 80  to host's port 80？

Any advice and suggestions will be greatly appreciated.

**Comment by fringefilmsoz** [comment]
How did you get around this @tuzkii ?

**Comment by kit101** [comment]
Do you solved this problem? @bugs-404

**Comment by bugs-404** [comment]
> Do you solved this problem? @bugs-404

Sorry, I just keep using port 80
