### ISSUE TITLE
the list of projects is showing infinite loading with console error

### ISSUE THREAD

**Issue by bikabdel** [Activiti/activiti-cloud-examples#106]
![Capture d’écran de 2019-10-10 15-27-03](https://user-images.githubusercontent.com/38707032/66578250-a9dad200-eb72-11e9-93c1-66668c38d3f3.png)

**Comment by tengzhexiao** [comment]
I have the same question .

**Comment by bananaspliff** [comment]
i have the same problem (firefox & chrome)

**Comment by bananaspliff** [comment]
fix it by changing "proxy pass" confg for nginx modeling service :

        proxy_pass         http://$upstream/$1?$args;

**Comment by bikabdel** [comment]
thank you @bananaspliff
