### ISSUE TITLE
make all  Exception at startup  java.net.UnknownHostException: zipkin

### ISSUE THREAD

**Issue by v-zhaozy** [Activiti/activiti-cloud-examples#125]
![image](https://user-images.githubusercontent.com/55344414/84565417-9f28aa80-ad9b-11ea-89de-1843cf9443fd.png)

**Comment by mteodori** [comment]
that exception is harmless, just ignore it if you don't have a zipkin server added to your docker compose or if it annoys you add the properties to disable sleuth/zipkin: https://cloud.spring.io/spring-cloud-sleuth/reference/html/appendix.html
