### ISSUE TITLE
commandTypes in postman collection

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/activiti-cloud-examples#87]
commandTypes are now uppercase and map to https://github.com/Activiti/Activiti/blob/28bcc750e1a826dca859af75b854e13fa7aa61ca/activiti-api/activiti-process-model-api/src/main/java/org/activiti/runtime/api/event/ProcessRuntimeEvent.java#L25

We need to update the postman collections as they still have the old mixed case names

**Comment by Salaboy** [comment]
This was fixed by Miguel already.

**Comment by Salaboy** [comment]
this was fixed by Miguel already.
