### ISSUE TITLE
activiti-cloud-sso-idm-kub in kubernetes/kubectl/infrastructure.yml fails to start.

### ISSUE THREAD

**Issue by saifuddinrangwala** [Activiti/activiti-cloud-examples#90]
Hi,

I wanted to give a quick try with activiti and tried to deploy using the k8s files given in this repository on the master branch.

So far tried to deploy only infrastructure.yml.  However the pod activiti-cloud-sso-idm-kub is failing to start as below:

<<snip>>
 kubectl describe pods activiti-cloud-sso-idm-kub-57d88f6b58-k4cfk -n activiti
Name:           activiti-cloud-sso-idm-kub-57d88f6b58-k4cfk
Namespace:      activiti
Node:           ip-172-20-36-188.ec2.internal/172.20.36.188
Start Time:     Thu, 16 Aug 2018 07:35:41 +0000
Labels:         app=infrastructure
                pod-template-hash=1384492614
                serviceType=sso-idm
Annotations:    <none>
Status:         Running
IP:             100.112.0.31
Controlled By:  ReplicaSet/activiti-cloud-sso-idm-kub-57d88f6b58
Containers:
  activiti-cloud-sso-idm-kub:
    Container ID:   docker://51c6a92b6404ef73a271ac8db8d15152b5ee8971eb66a176d15158fe3c39e205
    Image:          activiti/activiti-cloud-sso-idm:7-201802-EA
    Image ID:       docker-pullable://activiti/activiti-cloud-sso-idm@sha256:daa6a3f123a75d804553ede18493c1869e2c58cdd060e19b9df46158d29d9a74
    Port:           30081/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 16 Aug 2018 07:41:38 +0000
      Finished:     Thu, 16 Aug 2018 07:41:38 +0000
    Ready:          False
    Restart Count:  5
    Environment:
      PORT_OFFSET:  22001
      DB_VENDOR:    H2
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tcpvb (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  default-token-tcpvb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tcpvb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age               From                                    Message
  ----     ------                  ----              ----                                    -------
  Normal   Scheduled               6m                default-scheduler                       Successfully assigned activiti-cloud-sso-idm-kub-57d88f6b58-k4cfk to ip-172-20-36-188.ec2.internal
  Normal   SuccessfulMountVolume   6m                kubelet, ip-172-20-36-188.ec2.internal  MountVolume.SetUp succeeded for volume "default-token-tcpvb"
  Warning  Failed                  4m                kubelet, ip-172-20-36-188.ec2.internal  Failed to pull image "activiti/activiti-cloud-sso-idm:7-201802-EA": rpc error: code = Canceled desc = context canceled
  Warning  Failed                  4m                kubelet, ip-172-20-36-188.ec2.internal  Error: ErrImagePull
  Warning  FailedCreatePodSandBox  4m (x2 over 4m)   kubelet, ip-172-20-36-188.ec2.internal  Failed create pod sandbox.
  Normal   SandboxChanged          4m (x3 over 4m)   kubelet, ip-172-20-36-188.ec2.internal  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling                 3m (x4 over 6m)   kubelet, ip-172-20-36-188.ec2.internal  pulling image "activiti/activiti-cloud-sso-idm:7-201802-EA"
  Normal   Pulled                  3m (x3 over 4m)   kubelet, ip-172-20-36-188.ec2.internal  Successfully pulled image "activiti/activiti-cloud-sso-idm:7-201802-EA"
  Normal   Created                 3m (x3 over 4m)   kubelet, ip-172-20-36-188.ec2.internal  Created container
  Normal   Started                 3m (x3 over 4m)   kubelet, ip-172-20-36-188.ec2.internal  Started container
  Warning  BackOff                 1m (x14 over 3m)  kubelet, ip-172-20-36-188.ec2.internal  Back-off restarting failed container
<<snip>>

<<snip>>
kubectl logs -f activiti-cloud-sso-idm-kub-57d88f6b58-k4cfk -n activiti
standard_init_linux.go:178: exec user process caused "no such file or directory"
<<snip>>

If this configuration expected to work? Some of the services were getting deployed in default, which I change to my namespace "activiti". Is that causing the issue?

**Comment by ryandawsonuk** [comment]
@saifuddinrangwala have you looked at https://community.alfresco.com/community/bpm/blog/2018/08/13/getting-started-with-activiti-cloud-beta1 ? I'd suggest trying that approach as we intend to remove the kubectl descriptors in master in favour of the helm charts

**Comment by saifuddinrangwala** [comment]
Nope. thanks @ryandawsonuk . Thanks for the quick info.
